-- Create the core tables
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  email text,
  phone text,
  address text,
  business_name text,
  account_type text,
  created_at timestamptz default now() not null
);

create table if not exists applications (
  id bigint generated by default as identity primary key,
  application_id text unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  motorcycle_id bigint,
  motorcycle_name text,
  motorcycle_price numeric,
  repayment_frequency text,
  weekly_payment numeric,
  amount_paid numeric default 0,
  balance numeric default 0,
  status text default 'Under Review',
  created_at timestamptz default now() not null
);

create table if not exists motorcycles (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  available boolean default true,
  category text,
  created_at timestamptz default now() not null
);

insert into motorcycles (id, name, price, available, category)
values
  (1, 'Honda XR125', 425000, true, 'Commuter'),
  (2, 'TVS Apache RTR 200', 780000, true, 'Sport'),
  (3, 'Suzuki Giant Loop', 950000, true, 'Utility'),
  (4, 'Yamaha R15M', 1320000, true, 'Premium')
on conflict (id) do nothing;

-- Enable RLS
alter table profiles enable row level security;
alter table applications enable row level security;
alter table motorcycles enable row level security;

-- Automatically create a profile whenever an auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    first_name,
    last_name,
    phone,
    address,
    business_name,
    account_type,
    created_at
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'address', ''),
    coalesce(new.raw_user_meta_data ->> 'business_name', ''),
    coalesce(new.raw_user_meta_data ->> 'account_type', 'Hire-Purchase'),
    now()
  )
  on conflict (id) do update set
    email = excluded.email,
    first_name = coalesce(excluded.first_name, public.profiles.first_name),
    last_name = coalesce(excluded.last_name, public.profiles.last_name),
    phone = coalesce(excluded.phone, public.profiles.phone),
    address = coalesce(excluded.address, public.profiles.address),
    business_name = coalesce(excluded.business_name, public.profiles.business_name),
    account_type = coalesce(excluded.account_type, public.profiles.account_type);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Profiles: authenticated users can read all profiles for admin listing,
-- while owners can insert/update only their own record.
create policy "profiles_select_authenticated"
on profiles
for select
using (auth.role() = 'authenticated');

create policy "profiles_insert_owner"
on profiles
for insert
with check (auth.uid() = id);

create policy "profiles_update_owner"
on profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Applications: owners can manage own applications.
create policy "applications_select_owner"
on applications
for select
using (auth.uid() = user_id);

create policy "applications_insert_owner"
on applications
for insert
with check (auth.uid() = user_id);

create policy "applications_update_owner"
on applications
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Motorcycles: readable by authenticated users, insert/update only for admin flows.
create policy "motorcycles_select_authenticated"
on motorcycles
for select
using (auth.role() = 'authenticated');

create policy "motorcycles_insert_admin"
on motorcycles
for insert
with check (auth.role() = 'authenticated');

create policy "motorcycles_update_admin"
on motorcycles
for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

-- Optional: grant wider access for a future admin dashboard if needed.
-- If you prefer stricter admin-only access, replace the profiles_select_authenticated policy with a role check.
